# Generated by Django 5.2.8 on 2025-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donante',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='donacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='donacion',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('WOMPI', 'Wompi'), ('PAYU', 'PayU'), ('NEQUI', 'Nequi'), ('OTRO', 'Otro')], max_length=100, null=True),
        ),
    ]
