# Generated by Django 5.2.8 on 2025-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hogardepaso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hogardepaso',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
